version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: "@fortawesome/free-brands-svg-icons"
    versions:
    - ">= 5.15.a, < 5.16"
  - dependency-name: "@fortawesome/free-regular-svg-icons"
    versions:
    - ">= 5.15.a, < 5.16"
  - dependency-name: prettier
    versions:
    - ">= 2.1.a, < 2.2"
  - dependency-name: webpack
    versions:
    - 4.46.0
    - 5.22.0
    - 5.24.0
    - 5.24.1
    - 5.24.3
    - 5.25.0
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.30.0
    - 5.32.0
    - 5.34.0
    - 5.35.0
    - 5.36.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.34
    - 15.0.0
  - dependency-name: ts-loader
    versions:
    - 9.0.0
    - 9.1.0
  - dependency-name: core-js
    versions:
    - 3.10.2
  - dependency-name: buefy
    versions:
    - 0.9.7
  - dependency-name: "@babel/core"
    versions:
    - 7.13.1
    - 7.13.13
  - dependency-name: vue-i18n
    versions:
    - 8.24.1
  - dependency-name: "@vue/composition-api"
    versions:
    - 1.0.0-rc.4
  - dependency-name: css-loader
    versions:
    - 5.1.2
  - dependency-name: "@babel/runtime-corejs3"
    versions:
    - 7.13.3
    - 7.13.6
    - 7.13.9
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.0
    - 7.13.5
    - 7.13.9
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.1.0
  - dependency-name: "@babel/plugin-proposal-optional-chaining"
    versions:
    - 7.12.17
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.5
    - 1.3.7
  - dependency-name: moment-timezone
    versions:
    - 0.5.33
  - dependency-name: sass
    versions:
    - 1.32.5
    - 1.32.6
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
  - dependency-name: sass-loader
    versions:
    - 10.1.1
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: node
    versions:
    - 15.7.0.pre.alpine
