version: '3.3'

services:
  app:
    container_name: ci-syncroomplus-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./:/app:cached
    stdin_open: true
