name: ビルド検証
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        id: setup_node_id
        with:
          node-version: 18
          cache: yarn

      - uses: actions/cache@v3
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}-v6

      - run: echo '${{ toJSON(steps.node_modules_cache_id.outputs) }}'
      - run: echo '${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}'

      - if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - run: yarn build

      - run: yarn build-zip
