# DependabotがPRを作ったときに権限がなくてカバレッジレポートが投稿されないので設定
permissions:
  pull-requests: write
  issues: write
  repository-projects: write

name: テスト実行
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        id: setup_node_id
        with:
          node-version: 18
          cache: yarn

      - uses: actions/cache@v3
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - run: echo '${{ toJSON(steps.setup_node_id.outputs) }}'

      - if: ${{ steps.setup_node_id.outputs.cache-hit != 'true' }}
        run: yarn install --frozen-lockfile

      - uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: 'yarn'
          test-script: yarn run test:coverage
