name: テスト実行
on:
  pull_request:
  push:
    branches:
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore Cache
        uses: actions/cache@v3
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}-v7

      - run: echo '${{ toJSON(steps.node_modules_cache_id.outputs) }}'

      - name: Run yarn install
        if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        run: docker compose -f docker-compose.ci.yml run --rm app yarn install --frozen-lockfile

      - name: Run test
        run: docker compose -f docker-compose.ci.yml run --rm app yarn run test
